apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  index.html: |
{{ .Values.htmlContent | indent 4 }}
