apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app-chart.fullname" . }}
  labels:
    {{- include "web-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /usr/share/nginx/html
        - name: multitool
          image: "{{ .Values.image.multitool.repository }}:{{ .Values.image.multitool.tag }}"
          imagePullPolicy: {{ .Values.image.multitool.pullPolicy }}
          env:
            - name: HTTP_PORT
              value: "{{ .Values.service.multitoolPort }}"
          ports:
            - containerPort: {{ .Values.service.multitoolPort }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "web-app-chart.fullname" . }}-config
