apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-app
  template:
    metadata:
      labels:
        app: init-app
    spec:
      initContainers:
        - name: wait-for-service
          image: busybox:latest
          command:
            - sh
            - -c
            - 'for i in $(seq 1 30); do
                 wget -qO- http://10.152.183.215:80 && exit 0;
                 wget -qO- http://init-service:80 && exit 0;
                 echo waiting for service $i;
                 sleep 2;
               done;
               exit 1'
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
